FROM python:3.9-slim

WORKDIR /backend

COPY ./requirements.txt /backend/requirements.txt

RUN pip install --no-cache-dir -r /backend/requirements.txt 

COPY ./src /backend/src

CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "80", "--reload"]