name: Development

on:
  push:
    branches:
      - "backend/*"
      - "slack/*"
  pull_request:
    branches:
      - "backend/*"
      - "slack/*"

permissions:
  id-token: write
  contents: read

env:
  ENV_NAME: development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # TODO Optimize the Nodejs installation using GitHub Actions
      # TODO Optimize and cache node_modules
      - run: npm i -g pnpm
        working-directory: ./aws

      - run: pnpm i --no-frozen-lockfile --shamefully-hoist
        working-directory: ./aws

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::851725404161:role/GitHubRoleFor-access2justice-law-bot
        timeout-minutes: 3 # assuming an AWS role never takes that long, but error loops do

      - run: aws sts get-caller-identity

      - run: pnpm dlx cdk deploy 'LawBotBackendLambdaApiStack-*' --require-approval never
        working-directory: ./aws
        env:
          ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_EMBEDDING_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT }}
          AZURE_SEARCH_ENPOINT: ${{ secrets.AZURE_SEARCH_ENPOINT }}
          AZURE_SEARCH_INDEX_NAME: ${{ secrets.AZURE_SEARCH_INDEX_NAME }}
          AZURE_SEARCH_KEY: ${{ secrets.AZURE_SEARCH_KEY }}
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
          RUNNING_ENV: "development"

      - run: pnpm dlx cdk deploy 'LawBotSlackLambdaApiStack-*' --require-approval never
        working-directory: ./aws
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          AWS_API_CHAT_ENDPOINT: ${{ vars.AWS_API_CHAT_ENDPOINT }}
